services:
  - type: web
    name: ladybugnodes
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_URL
        sync: true
      - key: ADMIN_USERNAME
        sync: true
      - key: ADMIN_PASSWORD
        sync: true
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: true
    disk:
      name: ladybugnodes-data
      mountPath: /opt/render/project/data
      sizeGB: 1
